### ISSUE TITLE
Bristol pedestrian flow data

### ISSUE THREAD

**Issue by mpadge** [ATFutures/who-data#1]
@Robinlovelace I'm going to store the scripts for flow layer generation for [`upthat#21`](https://github.com/ATFutures/upthat/issues/21) here. One thing we'll need for Bristol is some kind of relative measure of train versus bus usage. At the very least, we'll have to feed in estimates of:

- Numbers of people getting off at Temple Meads per day
- Total bus ridership per day

Any idea where we might obtain such? Any more detailed data would of course also be beneficial.

**Comment by Robinlovelace** [comment]
Hi @mpadge not off the top of my head. I suggest we leave this one until after the flow layer data is up for the other cities. Bristol is a bonus.
